### PR TITLE
Added a server status

### PR DESCRIPTION
**Pull request by ZeroDevOfficial**
Just an idea

### CODE REVIEW

**Comment by ZeroDevOfficial** [comment]
@remotevase do you like? all you have to change is the `Server-IP here` and it will show a server in real time

**Comment by remotevase** [comment]
Thanks!

**Comment by ZeroDevOfficial** [comment]
@remotevase you might want to change the github.io page to .php because I changed it in this pull request

**Comment by remotevase** [comment]
What u mean?

**Comment by ZeroDevOfficial** [comment]
https://remotevase.github.io/OnePage-Website/

The website is php, it's not html anymore lol

**Comment by ZeroDevOfficial** [comment]
```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus
```

**Comment by remotevase** [comment]
lol yeah I know that...

**Comment by ZeroDevOfficial** [comment]
Ok just making sure you knew lol

**Comment by remotevase** [comment]
oh lol

**Pull request merged**
